### ISSUE TITLE
请求添加支持cdn加载的第三方库

### ISSUE THREAD

**Issue by MasterOfStar** [MuZhou233/Morecho-Typecho#2]
> 为保证资源可访问性，Morecho 主题使用的绝大部分第三方库都未使用 cdn，所以文件会比较大，在低配置服务器上也可能出现加载缓慢的情况

jsdelivr cdnjs bootcdn等都算比较稳的公共cdn，从理论上讲这些公共cdn出问题的概率远低于个人博客出问题的概率

**Comment by MuZhou233** [comment]
0.5 版本开始支持cdn，如果担心稳定性可以等稳定版
