### ISSUE TITLE
请求添加数学公式支持

### ISSUE THREAD

**Issue by widsnoy** [MuZhou233/Morecho-Typecho#3]
推荐KaTeX或者mathjax。

**Comment by MuZhou233** [comment]
0.5.1.0 已经部分支持了

**Comment by MuZhou233** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Morecho集成测试](https://trello.com/c/fazAcKtR/1-morecho%E9%9B%86%E6%88%90%E6%B5%8B%E8%AF%95)
